Removed scripts/.tests and updated README.md

diff --git a/current/scripts/.scripts/copy_new_loved_songs b/current/scripts/.scripts/copy_new_loved_songs
--- a/current/scripts/.scripts/copy_new_loved_songs
+++ b/current/scripts/.scripts/copy_new_loved_songs
@@ -9,14 +9,13 @@ out="$HOME/Desktop/.temp.mp3"
 
 n_songs=$(wc -l "$HOME/.mpd/playlists/new_loved_songs.m3u" | cut -d ' ' -f1)
 
-while read -r line; do
-     if [ -f "$line" ]; then
-          cp "$line" "$out"
-          song_to_phone "$out"
+while read -r song; do
+     if [ -f "$song" ]; then
+          song_to_phone "$song"
           # update loved songs playlist
-          echo "$line" >>"$old_songs"
+          echo "$song" >>"$old_songs"
      else
-          echo "$line" invalid 1>&2
+          echo "$song" invalid 1>&2
      fi
 done <"$new_songs"
 truncate -s 0 "$new_songs"
